# -*- coding: utf-8 -*-
"""app_ventas_retail.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/196ioaigqEzu8B0OQKvpQw78C7lYvZmJh
"""

# ==========================================================
# RetailMax - Predictor de Ventas (Streamlit App)
# ==========================================================


import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime, timedelta
import warnings

warnings.filterwarnings('ignore')

# ----------------------------------------------------------
# Configuración página
# ----------------------------------------------------------

st.set_page_config(
    page_title="RetailMax - Predictor de Ventas",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown("""
<style>
.main-header {
    font-size: 2.5rem;
    color: #1f77b4;
    text-align: center;
}
</style>
""", unsafe_allow_html=True)

# ----------------------------------------------------------
# Datos demo
# ----------------------------------------------------------

@st.cache_data
def cargar_datos_demo():

    np.random.seed(42)

    tiendas = [f"Tienda_{i:02d}" for i in range(1, 21)]
    fechas = pd.date_range(start='2024-01-01', periods=12, freq='W')

    data = []

    for tienda in tiendas:
        for fecha in fechas:
            data.append({
                'tienda_id': tienda,
                'fecha': fecha,
                'ventas_semanales': np.random.normal(15000, 3000),
                'promocion_activa': np.random.choice([0,1]),
                'inventario_inicial': np.random.normal(50000, 10000),
                'temperatura_promedio': np.random.normal(20, 8),
                'año': fecha.year,
                'mes': fecha.month,
                'semana': fecha.isocalendar().week,
                'dia_semana': fecha.dayofweek
            })

    return pd.DataFrame(data)

df_historico = cargar_datos_demo()

# ----------------------------------------------------------
# Modelo demo
# ----------------------------------------------------------

@st.cache_resource
def cargar_modelo():

    from sklearn.ensemble import RandomForestRegressor
    from sklearn.model_selection import train_test_split

    df = df_historico.copy()

    features = [
        'promocion_activa',
        'inventario_inicial',
        'temperatura_promedio',
        'año','mes','semana','dia_semana'
    ]

    X = df[features]
    y = df['ventas_semanales']

    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

    modelo = RandomForestRegressor()
    modelo.fit(X_train,y_train)

    return modelo, features

modelo, feature_columns = cargar_modelo()

# ----------------------------------------------------------
# Sidebar
# ----------------------------------------------------------

def crear_sidebar():

    st.sidebar.header("Configuración")

    tienda = st.sidebar.selectbox(
        "Tienda",
        df_historico['tienda_id'].unique()
    )

    fecha = st.sidebar.date_input(
        "Fecha predicción",
        datetime.now()
    )

    promocion = st.sidebar.radio("Promoción", [0,1])

    inventario = st.sidebar.slider("Inventario",20000,80000,50000)

    temperatura = st.sidebar.slider("Temperatura",-10,40,20)

    predecir = st.sidebar.button("Predecir")

    return {
        'tienda': tienda,
        'fecha': fecha,
        'promocion': promocion,
        'inventario': inventario,
        'temperatura': temperatura,
        'predecir': predecir
    }

parametros = crear_sidebar()

# ----------------------------------------------------------
# Predicción
# ----------------------------------------------------------

def hacer_prediccion(param):

    fecha = pd.to_datetime(param['fecha'])

    X_pred = pd.DataFrame({
        'promocion_activa':[param['promocion']],
        'inventario_inicial':[param['inventario']],
        'temperatura_promedio':[param['temperatura']],
        'año':[fecha.year],
        'mes':[fecha.month],
        'semana':[fecha.isocalendar().week],
        'dia_semana':[fecha.dayofweek]
    })

    pred = modelo.predict(X_pred)[0]

    return pred

# ----------------------------------------------------------
# Main
# ----------------------------------------------------------

def main():

    st.markdown('<h1 class="main-header">RetailMax Predictor</h1>', unsafe_allow_html=True)

    if parametros['predecir']:

        pred = hacer_prediccion(parametros)

        st.metric("Ventas predichas", f"${pred:,.0f}")

        datos = df_historico[df_historico['tienda_id']==parametros['tienda']]

        fig = px.line(datos, x='fecha', y='ventas_semanales',
                      title="Histórico vs Predicción")

        fig.add_scatter(
            x=[parametros['fecha']],
            y=[pred],
            mode='markers',
            name='Predicción'
        )

        st.plotly_chart(fig, use_container_width=True)

    else:

        st.subheader("Dashboard General")

        col1,col2,col3 = st.columns(3)

        col1.metric("Tiendas", df_historico['tienda_id'].nunique())
        col2.metric("Promedio ventas", f"${df_historico['ventas_semanales'].mean():,.0f}")
        col3.metric("Total ventas", f"${df_historico['ventas_semanales'].sum():,.0f}")

if __name__ == "__main__":
    main()
